POST http://localhost:8080/trips
Content-Type: application/json

{
    "title": "Druga oferta",
    "location": "(Sosnowiec, Polska)",
    "departure": "Łódź",
    "price": 1500,
    "transport": "Plane",
    "bargain": true
}