POST http://localhost:8080/trips
Content-Type: application/json

{
    "title": "Odwiedź stolicę Mexicas",
    "country": "Meksyk",
    "departure": "Łeba",
    "price": 1500000,
    "transport": "Ship",
    "bargain": true,
    "description": "Dawajcie wszystko czego chcą, albo was zabiją.",
    "travelTime": 800.0,
    "hotel": 1
}